### ISSUE TITLE
Cannot validate RCU Schemas

### ISSUE THREAD

**Issue by vinzinc-dev** [gianniceresa/docker-images#4]
Hi Gianni,

Having this issue while creating RCU schemas during first start

Processing command line ....
RCU exiting with status 100
ERROR validating RCU command and settings, can't validate RCU schemas creation
command: /opt/oracle/product/5.9.0/oracle_common/bin/rcu  -silent -createRepository -schemaPrefix nc80563b3398 -useSamePasswordForAllSchemaUsers true  -connectString 192.168.120.80:1521:orclpdb1 -dbUser sys -databaseType ORACLE -dbRole SYSDBA  -component STB -component MDS -component WLS -component OPSS -component BIPLATFORM -component IAU -component IAU_APPEND -component IAU_VIEWER -validate -f < /opt/oracle/product/5.9.0/_tmp_rcu.dat
Abort OAS configuration...

**Comment by gianniceresa** [comment]
Hi,
Is your database listening on 192.168.120.80:1521?
While not being impossible, I doubt your DB is running exactly on the same IP of my local sandbox DB.
You should customize the values of variables based on your environment. While everything else will work using the example values I posted, the database connection string and password should be the ones of your own database.

**Comment by vinzinc-dev** [comment]
Hi Gianni,

Thank you for the response. I am an analytics professional mainly and dev-ops isn't my strongest suite so please bear with me.

I am trying to run this on docker on windows. As far as I understand the image is built on top of an oracle linux instance on the docker itself right?

If that's the case, am I supposed to interrupt the image building somehow to install my database or is there an output of the build script itself that I am supposed to refer to?

**Comment by gianniceresa** [comment]
This image is only Oracle Analytics Server and nothing else. The product requires access to a database because it needs to create bunch of things there, that's what the RCU does.
The database isn't included in this image, mainly because it's a different product and also because the result would be huge (it is already big only with OAS, the image will be various Gb on disk).
If you want to install a database inside the same image, you have to define your own Dockerfile doing all the required tasks extending this one. That's why the "typical" usage is to run the database somewhere else: can be a cloud database or another container.
If you want to run it in Docker you can take the 19c EE of https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance .

**Comment by vinzinc-dev** [comment]
Ok ... I got it now. Also, I believe that its much more sensible to have the data stored in another instance. In that case I will install another database instance.

Thank you @gianniceresa. This was very helpful and the images are obviously helpful too. 👍🏻

**Comment by gianniceresa** [comment]
Yes, most of the cases the DB being separate is better (also because 1 DB = many OAS or other products).
The only real need for the DB to be inside the same Docker image as OAS could be for automated tests. In that case the Docker container you start has all it needs to perform the tests without any external dependency. But that's a whole different story.

**Comment by vinzinc-dev** [comment]
True ...

Also ... I did manage to get a db running in a docker and was immediately stuck with what you said above ... That I could use this db now for a lot of other applications too.

Also what you said about the docker image size makes a lot of sense ... after building the image and deploying the container my SSD got totally filled up. Had to spend some time figuring out ways to move docker images to another drive.

**Comment by gianniceresa** [comment]
By "design" to keep the Dockerfile readable (as it's also a good way to understand the install process of OAS) this image isn't optimized for size.
You could have a smaller size by optimizing the Dockerfile and reducing the layers, or by "squashing" the image.

There is a "-- squash" parameter that can be used with 'docker build', but it's still flagged as experimental (you can enable access to experimental features of Docker with a setting).

**Comment by vinzinc-dev** [comment]
The "squash" feature sounds interesting ... I will definitely read up on it.

But my very basic understanding of the Dockerfile is that you are simply installing the binaries of the components on a slim version of oracle linux. Where in there would you find more space to optimize?
Wondering if maybe the answer lies in the components itself ... maybe those components can have a lot of unnecessary features which we can make do without. I wouldn't know as I am very new to the whole ecosystem.
Or would the optimization be done in some other parameters?

**Comment by gianniceresa** [comment]
There are 3 distinct RUN commands and the result is at least 3 distinct layers (they are more than that as each command generate a layer), but compacting these 3 into a single one would gain lot of space already.

On the older OBIEE 12.2.1.2 image I did measure it. With the current Dockerfile design the image had these 3 layers being 4.83Gb, 5.13Gb and 8.44Gb. By adopting a single RUN command I had a single layer of 8.8Gb: 18.4Gb vs 8.8Gb. Already a good difference on disk. But the Dockerfile was unreadable and harder to maintain. That's why this image is larger but readable and easily customizable, it is really meant to democratize access to OAS and as a "learning platform".

**Comment by vinzinc-dev** [comment]
Apologies for the long breaks in the conversation ... work keeps taking over.

This is incredibly interesting and fascinating. Do you have access to any resources/examples of how to do this change? Or, purely from a learning standpoint, can I go through both versions of your OBIEE scripts ... that would be a great. I will of course not reuse it in any way without your permission. To be honest have no interest in OBIEE itself :D

Meanwhile I will give the entire OAS image setup a run today and check it out.

**Comment by gianniceresa** [comment]
I don't have that Dockerfile anymore. Keeping it simple: you have 3 RUN commands in the current file, those should become a single one. 2 are run by the same user and therefore it is very simple to merge them into a single one. The 3rd is executed by a different user, so all you need is to find how to execute commands as somebody else. There are few ways in linux for doing that.
Docker isn't magic, it's linux scripting in the end. So what works on your linux has chances to work in Docker (there are limits, but that's where Google generally helps in finding the "docker" way for it).
