### ISSUE TITLE
OAS bi_server fails to start.  It seems to be due to coherence server trying to scan all the ports

### ISSUE THREAD

**Issue by shiang-luong** [gianniceresa/docker-images#7]
I used the image built for OAS 6.4

OAS bi_server fails to start.  It seems to be due to coherence server trying to scan all the ports
I found the workaround that seems to work is to set the WKA (well known address) configuration.  I was wondering if there was a way to set a WKA address (or even to localhost) when starting the container.

**Comment by gianniceresa** [comment]
No idea what to tell you other than "it works on my computer" (well, on the 10 different environments where I did run it).
This image is provided without any support just as a quick shortcut to have an environment up and running. It "just" works with Docker (a recent version) without anything special.
If you have something special on your side, you will need to investigate and debug it on your side, because as I said "it works on my computer".

**Comment by shiang-luong** [comment]
Thanks for creating this.
